### ISSUE TITLE
Captured archive and log files have changed, regetting log files？

### ISSUE THREAD

**Issue by kakarotes** [erdemcer/kafka-connect-oracle#101]
The following error occurred when the program was running.
Captured archive and log files have changed, regetting log files.
After this kind of error occurs, Kafka's queue has no data. What can I do to deal with it

**Comment by kakarotes** [comment]
while (!this.closed && logMinerData.next()) {
            try {
              if ((sequence > 0) && (logMinerData.getInt("RBASQN") - sequence) > 1) {
                log.error("Captured archive and log files have changed, regetting log files");
                log.info("sequence：" + sequence);
                log.info("logMinerData.getInt(RBASQN)：" + logMinerData.getInt("RBASQN"));
                break;
              }

**Comment by kakarotes** [comment]
resolved

**Comment by sdu-zjl** [comment]
您好，能不能麻烦您分享下这个问题出现的原因和解决方案呀？
