### ISSUE TITLE
Error while creating the connector

### ISSUE THREAD

**Issue by sacoefrancis1986** [erdemcer/kafka-connect-oracle#20]
Moved all the necessary  jars to path. tried creating the below connector
curl -X POST http://localhost:8083/connectors -H "Content-Type: application/json" -d '{
"name":"oracle-logminer-connector",
"config": {
"connector.class":"com.ecer.kafka.connect.oracle.OracleSourceConnector",
"db.name.alias":"test",
"tasks.max":"1",
"topic":"cdctest",
"db.name":"EE",
"db.hostname":"localhost",
"db.port":"1521",
"db.user":"kminer",
"db.user.password":"kminerpass",
"db.fetch.size":"1",
"table.whitelist":"system.test_kafka",
"parse.dml.data":"true",
"reset.offset":"false",
"multitenant":"false"
}
}'

Getting below Error
{"name":"oracle-logminer-connector","connector":{"state":"RUNNING","worker_id":"127.0.1.1:8083"},"tasks":[{"id":0,"state":"FAILED","worker_id":"127.0.1.1:8083","trace":"org.apache.kafka.connect.errors.ConnectException: Instantiation error\n\tat org.apache.kafka.connect.runtime.isolation.Plugins.newPlugin(Plugins.java:78)\n\tat org.apache.kafka.connect.runtime.isolation.Plugins.newTask(Plugins.java:200)\n\tat org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:427)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1036)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:117)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:1051)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:1047)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: org.apache.kafka.common.KafkaException: Could not instantiate class com.ecer.kafka.connect.oracle.OracleSourceTask\n\tat org.apache.kafka.common.utils.Utils.newInstance(Utils.java:325)\n\tat org.apache.kafka.connect.runtime.isolation.Plugins.newPlugin(Plugins.java:76)\n\t... 10 more\nCaused by: java.lang.reflect.InvocationTargetException\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)\n\tat org.apache.kafka.common.utils.Utils.newInstance(Utils.java:321)\n\t... 11 more\nCaused by: java.lang.IllegalStateException: Cannot initialize kafka-connect-oracle SQL resources\n\tat com.ecer.kafka.connect.oracle.ConnectorSQL.<init>(ConnectorSQL.java:56)\n\tat com.ecer.kafka.connect.oracle.OracleSourceTask.<init>(OracleSourceTask.java:79)\n\t... 16 more\nCaused by: java.lang.NullPointerException\n\tat com.ecer.kafka.connect.oracle.ConnectorSQL.<init>(ConnectorSQL.java:42)\n\t... 17 more\n"}

Below is the java version:
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

Let me know further details needed?

Regards,
Francis

**Comment by kpmeen** [comment]
Seing the same things as you @sacoefrancis1986. I've located and fixed a few bugs yesterday and eventually managed to get past the NPE. But only with `parse.dml.data = false`. When trying to set it to true there seems to be other bugs or issues that cause the code to fail. Haven't had any luck in identifying the problem yet though.

**Comment by sacoefrancis1986** [comment]
Thanks @kpmeen  after setting it to parse.dml.data= false too same error.

{"name":"oracle-logminer-connector","connector":{"state":"RUNNING","worker_id":"127.0.1.1:8083"},"tasks":[{"id":0,"state":"FAILED","worker_id":"127.0.1.1:8083","trace":"org.apache.kafka.connect.errors.ConnectException: Instantiation error\n\tat org.apache.kafka.connect.runtime.isolation.Plugins.newPlugin(Plugins.java:78)\n\tat org.apache.kafka.connect.runtime.isolation.Plugins.newTask(Plugins.java:200)\n\tat org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:427)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1036)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:117)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:1051)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:1047)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: org.apache.kafka.common.KafkaException: Could not instantiate class com.ecer.kafka.connect.oracle.OracleSourceTask\n\tat org.apache.kafka.common.utils.Utils.newInstance(Utils.java:325)\n\tat org.apache.kafka.connect.runtime.isolation.Plugins.newPlugin(Plugins.java:76)\n\t... 10 more\nCaused by: java.lang.reflect.InvocationTargetException\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)\n\tat org.apache.kafka.common.utils.Utils.newInstance(Utils.java:321)\n\t... 11 more\nCaused by: java.lang.IllegalStateException: Cannot initialize kafka-connect-oracle SQL resources\n\tat com.ecer.kafka.connect.oracle.ConnectorSQL.<init>(ConnectorSQL.java:56)\n\tat com.ecer.kafka.connect.oracle.OracleSourceTask.<init>(OracleSourceTask.java:79)\n\t... 16 more\nCaused by: java.lang.NullPointerException\n\tat com.ecer.kafka.connect.oracle.ConnectorSQL.<init>(ConnectorSQL.java:42)\n\t... 17 more\n"}],"type":"source"}

Regards,
Francis

**Comment by kpmeen** [comment]
@sacoefrancis1986 yes, as mentioned I had to fix some of the NPE's to get it working with `parse.dml.data=false`.
I've been trying to get it working with the value set to `true`. But there are a lot of problems in the code with unsafe access to several different variables still. I have a "working" version locally now, but it does not populate the `data.value` or `data.before` fields. The reason seems to be that the code is not able to identify the proper dictionary before processing data.

**Comment by erdemcer** [comment]
Hi,
I am working on this issue . I think parse.dml.data property is not responsible. Could you please give some detail about your  environment like  Oracle version , multitenancy exists  ?
Thanks.

**Comment by sacoefrancis1986** [comment]
Thanks @erdemcer  am using below oracle version
Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
PL/SQL Release 11.2.0.1.0 - Production
CORE	11.2.0.1.0	Production
TNS for Linux: Version 11.2.0.1.0 - Production
NLSRTL Version 11.2.0.1.0 - Production

no multitenancy exist.
oracle is running  on   docker   

Regards,
Francis

**Comment by erdemcer** [comment]
Thanks for information , let me give some time to fix some errors related with this.

**Comment by erdemcer** [comment]
Could you please test it again with new commit ? 

Thanks.

**Comment by sacoefrancis1986** [comment]
@erdemcer  Thanks it worked on new commit.
