### ISSUE TITLE
ERROR Failed to start task oracle-logminer-connector-0 as distributed connector

### ISSUE THREAD

**Issue by andrew6071** [erdemcer/kafka-connect-oracle#22]
Hi, 

I'm trying to start the connector as a distributed connector using the confluent platform, but get the following error

[2019-11-28 16:22:20,782] ERROR Failed to start task oracle-logminer-connector-0 (org.apache.kafka.connect.runtime.Worker:464)
Nov 28 16:22:20 zoo2 connect-distributed[15253]: org.apache.kafka.connect.errors.ConnectException: Instantiation error
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at org.apache.kafka.connect.runtime.isolation.Plugins.newPlugin(Plugins.java:78)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at org.apache.kafka.connect.runtime.isolation.Plugins.newTask(Plugins.java:200)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:427)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1036)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:117)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:1051)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:1047)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at java.lang.Thread.run(Thread.java:748)
Nov 28 16:22:20 zoo2 connect-distributed[15253]: Caused by: org.apache.kafka.common.KafkaException: Could not instantiate class com.ecer.kafka.connect.oracle.OracleSourceTask
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:325)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at org.apache.kafka.connect.runtime.isolation.Plugins.newPlugin(Plugins.java:76)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         ... 10 more
Nov 28 16:22:20 zoo2 connect-distributed[15253]: Caused by: java.lang.reflect.InvocationTargetException
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:321)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         ... 11 more
Nov 28 16:22:20 zoo2 connect-distributed[15253]: Caused by: java.lang.IllegalStateException: Cannot initialize kafka-connect-oracle SQL resources
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at com.ecer.kafka.connect.oracle.ConnectorSQL.<init>(ConnectorSQL.java:56)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at com.ecer.kafka.connect.oracle.OracleSourceTask.<init>(OracleSourceTask.java:79)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         ... 16 more
Nov 28 16:22:20 zoo2 connect-distributed[15253]: Caused by: java.lang.NullPointerException
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         at com.ecer.kafka.connect.oracle.ConnectorSQL.<init>(ConnectorSQL.java:42)
Nov 28 16:22:20 zoo2 connect-distributed[15253]:         ... 17 more

Andrew

**Comment by andrew6071** [comment]
i'm using openjdk 8, and connecting to 12.2 database hosted on aws rds

**Comment by andrew6071** [comment]
ooops i've just noticed that i was missing a library, in the target/*/share/java folder there is a jsql parser library which isn't mentioned in your docs (i don't think)

its now managed to get a bit further but complains about the following

org.apache.kafka.connect.errors.ConnectException: Error at database tier, Please check : java.sql.SQLSyntaxErrorException: ORA-01031: insufficient privileges
ORA-06512: at "SYS.DBMS_LOGMNR", line 58
ORA-06512: at line 2

	at com.ecer.kafka.connect.oracle.OracleSourceTask.start(OracleSourceTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:202)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:74

**Comment by andrew6071** [comment]
ok, i needed to grant 

execute on DBMS_LOGMNR to my user

and logminer

**Comment by erdemcer** [comment]
Actually ,i have removed ConnectorSQL file from code which causes error which like yours . You can get new updated code .
Thanks.

**Comment by maeri** [comment]
Hello @andrew6071 

Same issue for me. 

> ok, i needed to grant
> 
> execute on DBMS_LOGMNR to my user
> 
> and logminer

Connecting as kminer , but still got complaints on 
org.apache.kafka.connect.errors.ConnectException: Error at database tier, Please check : java.sql.SQLSyntaxErrorException: ORA-01031: insufficient privileges
ORA-06512: at "SYS.DBMS_LOGMNR", line 58

even doing 

grant execute on SYS.DBMS_LOGMNR to kminer; 

from SYS user. That would help me a lot. Kind regards.

**Comment by erdemcer** [comment]
Actually  execute_catalog_role privilege contains this grant . But i will take care of it .
Thanks

**Comment by davyam** [comment]
Same issue with Oracle 12.1.

@erdemcer you are right, execute_catalog_role is the privilege required to execute SYS.DBMS_LOGMNR.START_LOGMNR, but even with the grants I still getting this error:

```
INFO WorkerSourceTask{id=oracle-logminer-connector-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:414)
[2021-01-18 18:46:53,616] ERROR WorkerSourceTask{id=oracle-logminer-connector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
org.apache.kafka.connect.errors.ConnectException: Error at database tier, Please check : java.sql.SQLSyntaxErrorException: ORA-01031: insufficient privileges
ORA-06512: at "SYS.DBMS_LOGMNR", line 58
ORA-06512: at line 2
        at com.ecer.kafka.connect.oracle.OracleSourceTask.start(OracleSourceTask.java:219)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:198)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2021-01-18 18:46:53,618] ERROR WorkerSourceTask{id=oracle-logminer-connector-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:178)
```

Guys, any tip?

**Comment by davyam** [comment]
> Same issue with Oracle 12.1.
> 
> @erdemcer you are right, execute_catalog_role is the privilege required to execute SYS.DBMS_LOGMNR.START_LOGMNR, but even with the grants I still getting this error:
> 
> ```
> INFO WorkerSourceTask{id=oracle-logminer-connector-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:414)
> [2021-01-18 18:46:53,616] ERROR WorkerSourceTask{id=oracle-logminer-connector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
> org.apache.kafka.connect.errors.ConnectException: Error at database tier, Please check : java.sql.SQLSyntaxErrorException: ORA-01031: insufficient privileges
> ORA-06512: at "SYS.DBMS_LOGMNR", line 58
> ORA-06512: at line 2
>         at com.ecer.kafka.connect.oracle.OracleSourceTask.start(OracleSourceTask.java:219)
>         at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:198)
>         at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
>         at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
> [2021-01-18 18:46:53,618] ERROR WorkerSourceTask{id=oracle-logminer-connector-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:178)
> ```
> 
> Guys, any tip?

The DBA solved this issue with a 

`grant LOGMINING to kminer;`

\o/
