### ISSUE TITLE
is there tutorial, step to implement it 

### ISSUE THREAD

**Issue by priatmoko** [erdemcer/kafka-connect-oracle#37]
Can I find complete tutorial of using kafka-connect-oracle as alternative for OGG.

Thanks

**Comment by erdemcer** [comment]
Hi,
Only tutorial about this connector is Readme. It contains details to implement. What kind of document , you would like to have ?
Thanks

**Comment by priatmoko** [comment]
Hi,
Thank you very much for your response.
Actually I am very new in kafka.. 
I have followed documentation until database configuration and it is done.
I still try to understand the configuration in kafka confluent, I have not found the tutorial about configuring kafka that implement kafka-connect-oracle.
Thanks

**Comment by erdemcer** [comment]
Have you created OracleSourceConnector.properties file ?

**Comment by priatmoko** [comment]
Not yet, I still try to understand about apache kafka and kafka confluent. I have successfully installed apache kafka and start making topics, producer, and consumer like in documentation, but I think I need to install kafka confluent package. 
If you have any article or tutorial for newbie like me , you can share it.

Thank you very much.

**Comment by erdemcer** [comment]
Hi,
If you are able to start zookeeper , kafka and create topics and consume messages , you do not have to install kafka confluent package . Confluent kafka package contains all binaries you have already installed. But still instered following URL can be guide,
https://docs.confluent.io/current/installation/installing_cp/zip-tar.html#prod-kafka-cli-install
Thanks

**Comment by priatmoko** [comment]
Hi Erdemcer,
Big thanks for your help. 

Best Regards,
