### ISSUE TITLE
Question about START_LOGMNR only with startscn

### ISSUE THREAD

**Issue by ziyan1991** [erdemcer/kafka-connect-oracle#38]
Hey,
I was trying to use this connector, it can connect to the database. However it stuck just before the log -- "logminer started successfully". I tried to run the `start_logmnr` and select from `v$logmnr_contents` in the plsql -- I printed the sql in log. the select v$logmnr_contents sql was never ended. 
Here is the START_LOGMNR sql:
```sql
begin
  DBMS_LOGMNR.START_LOGMNR(STARTSCN => 14974213611,
                           OPTIONS  => DBMS_LOGMNR.SKIP_CORRUPTION +
                                       DBMS_LOGMNR.NO_SQL_DELIMITER +
                                       DBMS_LOGMNR.NO_ROWID_IN_STMT +
                                       DBMS_LOGMNR.DICT_FROM_ONLINE_CATALOG +
                                       DBMS_LOGMNR.CONTINUOUS_MINE +
                                       DBMS_LOGMNR.COMMITTED_DATA_ONLY +
                                       dbms_logmnr.STRING_LITERALS_IN_STMT);
end;
```

Here is my search for v$logmnr_contents
```sql
SELECT thread#,
       scn,
       start_scn,
       nvl(commit_scn, scn) commit_scn,
       (xidusn || '.' || xidslt || '.' || xidsqn) AS xid,
       timestamp,
       operation_code,
       operation,
       status,
       SEG_TYPE_NAME,
       info,
       seg_owner,
       table_name,
       username,
       sql_redo,
       row_id,
       csf,
       TABLE_SPACE,
       SESSION_INFO,
       RS_ID,
       RBASQN,
       RBABLK,
       SEQUENCE#,
       TX_NAME,
       SEG_NAME,
       SEG_TYPE_NAME
  FROM v$logmnr_contents
 WHERE OPERATION_CODE in (1, 2, 3)
   and nvl(commit_scn, scn) >= 0
   and ((SEG_OWNER = 'sfboa2015' and TABLE_NAME = 'ds_inst'))
   and not ((SEG_OWNER = 'sfboa2015' and TABLE_NAME = 'z_user_t'));
```

Not user if somebody else run into the same problem.

**Comment by ziyan1991** [comment]
BTW, I am using oracle version as printed in the log 
```
Connected to database version 112040
```

**Comment by erdemcer** [comment]
Hi,
After connector started is there any DML occured in db ? 
Thanks

**Comment by ziyan1991** [comment]
Yes, I use plsql edit one data and commit the change, however there is no message received from kafka.

Thanks

**Comment by erdemcer** [comment]
And what is your fetch size in connector config ?

**Comment by ziyan1991** [comment]
here is my configuration file

```
name=oracle-logminer-connector
connector.class=com.ecer.kafka.connect.oracle.OracleSourceConnector
db.name.alias=test
tasks.max=1
topic=test-oracle
db.name=ORCL
db.hostname=192.168.0.170
db.port=1521
db.user=sfboa2015
db.user.password=sfboa2015
db.fetch.size=1
table.whitelist=sfboa2015.ds_inst
table.blacklist=sfboa2015.z_user_t
parse.dml.data=true
reset.offset=false
multitenant=false
```

**Comment by erdemcer** [comment]
From pl/sql v$logmnr_contents never ends , because of CONTINUOUS_MINE attribute. 
According to your configuration everything seems OK. Could you please start logmnr without CONTINUOUS_MINE attribute and try to observe there is  a record in logmnr_contents you have created.
Thanks

**Comment by ziyan1991** [comment]
It asked me to add logfile, if I delete the CONTINUOUS_MINE  attribute
```sql
begin
  DBMS_LOGMNR.START_LOGMNR(STARTSCN => 14978236306,
                           OPTIONS  => DBMS_LOGMNR.SKIP_CORRUPTION +
                                       DBMS_LOGMNR.NO_SQL_DELIMITER +
                                       DBMS_LOGMNR.NO_ROWID_IN_STMT +
                                       DBMS_LOGMNR.DICT_FROM_ONLINE_CATALOG +
                                       DBMS_LOGMNR.COMMITTED_DATA_ONLY +
                                       dbms_logmnr.STRING_LITERALS_IN_STMT);
end;

```

**Comment by ziyan1991** [comment]
should I just comment this `if` condition.
```java
if (dbVersion>=ORA_DESUPPORT_CM_VERSION){}
```
which make the parameter --`oraDeSupportCM` always true.

**Comment by erdemcer** [comment]
This parameter is used for 19c and later versions because , Continuous_mine attribute is desupported with 19c . I do not suggest comment it if you are using lower version .

In order to start logmnr without CM attribute 
`begin
   dbms_logmnr.add_log_file(logfilename=>'$YOUR_LOGFILE_NAME',options=>dbms_logmnr.new);
 end;
`
YOUR_LOG_FILE_NAME can be selected following sqls

> select name from v$archived_log where 14978236306 between FIRST_CHANGE# and next_CHANGE#
select member from v$log v1 join v$logfile v2 on v2.group#=v1.group# where 14978236306 between FIRST_CHANGE# and next_CHANGE#

**Comment by ziyan1991** [comment]
Thanks for your help. 

The problem have been solved. I used the sql in your reply and found the value of both `SEG_OWNER ` and `TABLE_NAME ` columns are uppercase. Then I changed the configuration from `table.whitelist=sfboa2015.ds_inst` to `table.whitelist=SFBOA2015.DS_INST`. After changing, the committed data can be transfered to kafka correctly. 

Again, Thank for your help.

**Comment by erdemcer** [comment]
Hi,
Glad to see it has been solved. I will fix it in code .
Thanks.
