### ISSUE TITLE
ORA-00942: table or view does not exist

### ISSUE THREAD

**Issue by irfanr** [erdemcer/kafka-connect-oracle#47]
Hi,

This error is suddenly occurred on connector tasks status:

`ORA-00942: table or view does not exist\n\n\tat com.ecer.kafka.connect.oracle.OracleSourceTask.start(OracleSourceTask.java:175)
`

I'm sure that the user setup in the connector have privileges for logminer, since it went just fine before this. Do you have any idea on what should I check? Thanks.

**Comment by erdemcer** [comment]
Hi,
Firstly you should check db side with logminer user you are using for connector. Could you please check privileges of user ?

**Comment by irfanr** [comment]
Hi,

It is working just fine until couple days ago, when it didn't capture any event. And when I restarted the task, the status showing error like above. 

I realise that I probably didn't using the latest connector build (built from source code), so I try to build it with the latest source code :https://github.com/erdemcer/kafka-connect-oracle/commit/287efb9760b601c49ed75c4e8dd5cacf9d04b5de. 

FYI, here is my connector config:
```json
{
  "name": "dev-opus-test",
  "connector.class": "com.ecer.kafka.connect.oracle.OracleSourceConnector",
  "reset.offset": "true",
  "db.hostname": "10.71.35.191",
  "db.user": "customer",
  "db.user.password": "somepassword",
  "db.port": "1521",
  "db.name": "mysid",
  "db.name.alias": "dev-opus-test",
  "db.fetch.size": "1",
  "tasks.max": "1",
  "table.whitelist": "CUSTOMER.TEST_KAFKA_CONNECT",
  "table.blacklist": "",
  "start.scn": "",
  "multitenant": "false",
  "topic": "",
  "parse.dml.data": "true"
}
```

After I update the jar file with the latest build, the task status shows no error (it is said 'running'). I try to access the connect.log, it shows no ERROR level on it. 

```
[2020-04-15 09:25:55,727] INFO WorkerSourceTask{id=dev-opus-test-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:397)
[2020-04-15 09:25:55,728] INFO WorkerSourceTask{id=dev-opus-test-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:414)
[2020-04-15 09:26:05,728] INFO WorkerSourceTask{id=dev-opus-test-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:397)
[2020-04-15 09:26:05,729] INFO WorkerSourceTask{id=dev-opus-test-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:414)
[2020-04-15 09:26:15,729] INFO WorkerSourceTask{id=dev-opus-test-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:397)
[2020-04-15 09:26:15,729] INFO WorkerSourceTask{id=dev-opus-test-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:414)
```

I try to print the sql statements probably will be run by the connector (CMMIW):

```sql
begin
DBMS_LOGMNR.START_LOGMNR(STARTSCN => 7412139391712,OPTIONS =>  DBMS_LOGMNR.SKIP_CORRUPTION+DBMS_LOGMNR.NO_SQL_DELIMITER+DBMS_LOGMNR.NO_ROWID_IN_STMT+DBMS_LOGMNR.DICT_FROM_ONLINE_CATALOG + DBMS_LOGMNR.CONTINUOUS_MINE+DBMS_LOGMNR.COMMITTED_DATA_ONLY+dbms_logmnr.STRING_LITERALS_IN_STMT)
; end;

SELECT thread#, scn, start_scn, nvl(commit_scn,scn) commit_scn ,(xidusn||'.'||xidslt||'.'||xidsqn) AS xid,timestamp, operation_code, operation,status, SEG_TYPE_NAME ,info,seg_owner, table_name, username, sql_redo ,row_id, csf, TABLE_SPACE, SESSION_INFO, RS_ID, RBASQN, RBABLK, SEQUENCE#, TX_NAME, SEG_NAME, SEG_TYPE_NAME
FROM  v$logmnr_contents
WHERE
OPERATION_CODE in (1,2,3,5)
and nvl(commit_scn,scn)>=7412139391712
and ((SEG_OWNER='CUSTOMER' and TABLE_NAME='TEST_KAFKA_CONNECT'));

begin
SYS.DBMS_LOGMNR.END_LOGMNR;
end;
```
I'm using below SCN as mentioned in the connect.log file:

`[2020-04-15 09:25:46,864] INFO dev-opus-test|Getting current scn from database 7412139391712 (com.ecer.kafka.connect.oracle.OracleSourceTask:184)`

And when I try to execute the select statement (after executing DBMS_LOGMNR.START_LOGMNR successfully), it is just running endlessly without any result. 

Do you have any suggestion on how is the best way to check it through the database? Thanks.

**Comment by erdemcer** [comment]
Hi,
To get result from v$logmnr_contents dbms_logmnr.start_logmnr must be executed without CONTINUOUS_MINE option.But you have to add log or archivelog files with dbms_logmnr.add_logfile procedure. Then you can execute dbms_logmnr.start_logmnr .
Thanks

**Comment by erdemcer** [comment]
Hi,
is there any update ?

**Comment by irfanr** [comment]
Hi,

Sorry for late reply. I haven't had a chance to try logminer query. But for _ORA-00942: table or view does not exist_ error, I have confirmed that the DBA forgot to add the necessary privilege mentioned in the README for the user. Thanks for the help and support!  :thumbsup:

**Comment by erdemcer** [comment]
Thanks
