### ISSUE TITLE
how does connector run in distributed mode

### ISSUE THREAD

**Issue by ayida** [erdemcer/kafka-connect-oracle#48]
hello, i have a question,
can this connector run  in distributed mode?

first ,i use `connect-standalone.sh & OracleSourceConnector.properties`  run success,
then ,i try to modify `OracleSourceConnector.properties`  to `OracleSourceConnector.json`, then use rest api `POST /connectors` to create this connector ,it runs well, no  error log 
but can not product message to kafka 
need help .thanks 

and this is my config
```
{
  "name": "oracle-logminer-connector",
  "config": {
    "connector.class": "com.ecer.kafka.connect.oracle.OracleSourceConnector",
    "db.name.alias":"orcl",
    "tasks.max":"1",
    "topic": "OracleAsyncData",
    "db.name": "orcl",
    "db.hostname": "192.168.0.82",
    "db.port": "11521",
    "db.user": "platform_zx",
    "db.user.password": "platform_zx",
    "db.fetch.size": "100",
    "table.whitelist": "PLATFORM_ZX.*",
    "table.blacklist": "",
    "parse.dml.data": "true",
    "reset.offset": "true",
    "start.scn": "",
    "multitenant": "false"
  }
}
```

**Comment by erdemcer** [comment]
Let me check it please .

**Comment by ayida** [comment]
i modify config  `db.fetch.size`  value 100 to 1, then ran success, i think i need to read the document about this configs, thanks

**Comment by erdemcer** [comment]
Glad to hear that
