### ISSUE TITLE
what' s the use of sourcePartition？And How can I customize partitions？Thanks.

### ISSUE THREAD

**Issue by yymoxiaochi** [erdemcer/kafka-connect-oracle#51]
**Q1:**I don't know what' s the use of sourcePartition?
In the code ,all sourcePartition is
 `Collections.singletonMap(LOG_MINER_OFFSET_FIELD, dbName);` ,  
and The messages is divided into four partitions (All partitions).

**Q2:** And if I want to specify a partition ， I know I can use this the constructor:
` public SourceRecord(Map<String, ?> sourcePartition, Map<String, ?> sourceOffset, String topic, Integer partition, Schema valueSchema, Object value) 
{
        this(sourcePartition, sourceOffset, topic, partition, (Schema)null, (Object)null, valueSchema, value);
    }`
But , I don't know how many partitions there are ？ Is there an API in there(kafka connect)?

**Q3:** I'm not sure how the other constructors work, right?  Is the parameter 'key' the 'key' used in the kafka DefaultPartitioner?
` public SourceRecord(Map<String, ?> sourcePartition, Map<String, ?> sourceOffset, String topic, Integer partition, Schema keySchema, Object key, Schema valueSchema, Object value, Long timestamp, Iterable<Header> headers)
 {
        super(topic, partition, keySchema, key, valueSchema, value, timestamp, headers);
        this.sourcePartition = sourcePartition;
        this.sourceOffset = sourceOffset;
    }`

` public int partition(String topic, Object key, byte[] keyBytes, Object value, byte[] valueBytes, Cluster cluster) {}`

Thank you very much ..

**Comment by yymoxiaochi** [comment]
Hi ?   could you give me some support ? thanks ..

**Comment by erdemcer** [comment]
Hi,
I would like to answer your questions with following answers
**A1:** Sourcepartition and sourceoffset can be used to keep track of sourcerecords data.Sourcepartition can be single row like table_name , database_name and sourceoffset can be map shows where data came from.
In this connector i am using sourcepartition equals to dbname and sourceoffset is a map which contains last fetched rows detail like scn,commit_scn and rowid.

**A2:** You can create topic with how many partitions this topic will have. You can describe topic with following command
``` kafka-topics --zookeeper server_name:2181 --topic TOPIC_NAME --describe ```

**A3:** I am using this connector with this constructor which data is seperated by key into partitions.After creating topic with n partitions connector seperate data
with this string key.
For example single topic with 72 partitions and key is table_names .

Thanks

**Comment by yymoxiaochi** [comment]
Wow ...  Thank you very much for your help.

**Comment by yymoxiaochi** [comment]
Hi ,I hava a new problem .
 how to stop a tasks? for example ,I want to get the data between 10 and 20 of the SCN. After that, the connector will still drop this method:
`while(!this.closed && logMinerData.next()){ ... }`
Is there a way to stop the task? In other words, is there a way to know that the task is complete ？
In the kafka connect API ，there is only one way to stop a connector, and the only way I can think of is to use this API to stop the current connector, but I don't know if all tasks in this connector are completed

**Comment by yymoxiaochi** [comment]
And why need` nvl(commit_scn,scn)>=? ` in OracleConnectorSQL.LOGMINER_SELECT_WITHSCHEMA ?
Didn't we restrict startScn at startLomginer？
`begin DBMS_LOGMNR.START_LOGMNR(STARTSCN => ?,`

And SkipRecord seems to have done the same thing.
Are these three filtering a class of data？
PLS :)

**Comment by yymoxiaochi** [comment]
I user this config 
`    private Long getStartScn(String miningWay) throws SQLException {
        Long startScn;
        switch (miningWay) {
            case MiningWay.CONTINUE:
                startScn = getStartScnContinue();
                break;
            case MiningWay.CURRENT:
                startScn = getStartScnCurrent();
                break;
            case MiningWay.SCN:
                startScn = cdcContext.getStartScn();
                cdcContext.setSkipRecord(false);
                break;
            default:
                throw new ConnectException("Error For Get StartScn,Please Check configuration");
        }
        if (startScn == null || startScn == 0L) {
            throw new ConnectException("Error For Get StartScn,Please Check configuration\"");
        }
        return startScn;
    }`

But I don't know when to SkipRecord...

**Comment by erdemcer** [comment]
Hi,
If your database version is under 19c connector open logminer with COMMITTED_DATA_ONLY attribute and data coming from logmnr_contents are commit_scn ordered not scn ordered. Because of this i am using commit_scn. But logminer start script use SCN and restarting connector can cause to capture same DML events.To block this connector starts from first SCN of last opened redo or archivelog and skip records until last captured DML.
Thanks.
