### ISSUE TITLE
Update Operation won't catch full Data and Before Object in Kafka Message

### ISSUE THREAD

**Issue by irfanr** [erdemcer/kafka-connect-oracle#52]
Hi,

There is a case where the Update Operation only displaying properties data which being updated, but not all the data. For example, this is one of the SQL Statement:

```sql
update CUSTOMER.NCS_JOB_INFORMATION 
set JOB_STATUS = 'FINISHED', JOB_FINISH_TIME = TIMESTAMP ' 2020-04-24 23:02:54' 
where 
JOB_STATUS = 'RUNNING' and JOB_FINISH_TIME IS NULL;
```

will only displaying data properties which are updated, but not with the one which is not updated:

```javascript
  "payload": {
    "SCN": 7421302812492,
    "SEG_OWNER": "CUSTOMER",
    "TABLE_NAME": "NCS_JOB_INFORMATION",
    "TIMESTAMP": 1587956980000,
    "SQL_REDO": "update \"CUSTOMER\".\"NCS_JOB_INFORMATION\" set \"JOB_STATUS\" \u003d \u0027FINISHED\u0027, \"JOB_FINISH_TIME\" \u003d TIMESTAMP \u0027 2020-04-27 10:08:54\u0027 where \"JOB_STATUS\" \u003d \u0027FINISHED\u0027 and \"JOB_FINISH_TIME\" \u003d TIMESTAMP \u0027 2020-04-24 23:02:54\u0027",
    "OPERATION": "UPDATE",
    "data": {
      "JOB_NAME": null,
      "JOB_DESC": null,
      "JOB_PARAMETER": null,
      "JOB_STATUS": "FINISHED",
      "JOB_START_DATE": null,
      "JOB_FINISH_TIME": 1587956934000
    },
    "before": {
      "JOB_NAME": null,
      "JOB_DESC": null,
      "JOB_PARAMETER": null,
      "JOB_STATUS": "FINISHED",
      "JOB_START_DATE": null,
      "JOB_FINISH_TIME": 1587744174000
    }
  }
```
Unfortunately, we need all data properties to be filled (even the one which aren't updated). Do you have any idea on how to do this? Thanks.

**Comment by erdemcer** [comment]
Hi,
Firstly could you please check supplemental logging from your v$database view ?

```sql 
select v."SUPPLEMENTAL_LOG_DATA_MIN",v."SUPPLEMENTAL_LOG_DATA_PK",v."SUPPLEMENTAL_LOG_DATA_UI",
       v."SUPPLEMENTAL_LOG_DATA_ALL"
 from v$database v ```

**Comment by irfanr** [comment]
Hi,

This is the result from the above select statement:

```
SUPPLEME SUP SUP SUP
-------- --- --- ---
YES      NO  NO  NO 
```

**Comment by erdemcer** [comment]
Hi,
Could you please execute following command mentioned in Readme in order to capture all fields of data and retest the issue ?
alter database add supplemental log data (all) columns;
Thanks

**Comment by irfanr** [comment]
Hi,

Sorry for late reply. I have confirmed that this solved my problems. Many thanks for the great support @erdemcer! :thumbsup:
