### ISSUE TITLE
update clob fields  

### ISSUE THREAD

**Issue by schdai** [erdemcer/kafka-connect-oracle#53]
if you update a clob field, the clob contentes will appear in the redo_sql , not in data section in json.

"SQL_REDO": "update \"XTHIS\".\"TESTA\" set \"CL\" = 'aaaaaaaaa'      ' where \"DRUG_CODE\" = '1'",                                                                                                                                                      
"OPERATION": "UPDATE",
"data": {
			"DRUG_CODE": "1",
			"CODE1": null,
			"C": null,
			"CL": null
		},
"before": {
			"DRUG_CODE": "1",
			"CODE1": null,
			"C": null,
			"CL": null
		}

**Comment by erdemcer** [comment]
Hi,
Because of CLOB column which is  updated is  not in where expressions  , capture can not write it  data section. Capture assumes all columns are in where . Connector needs development for this issue . I am taking this issue to plan.
Thanks.

**Comment by schdai** [comment]
thanks for your reply.
