### ISSUE TITLE
where to start after crash of kafka connect oracle

### ISSUE THREAD

**Issue by schdai** [erdemcer/kafka-connect-oracle#55]
I found that after  kafka connect had crashed or stopped , then start it now, it will start new capture from now on. So, some data will miss in kafka topic.  How to capture from the timepoint it crash?

**Comment by erdemcer** [comment]
Hi,
if "reset.offset"  configuration property is set to true , every time connector start it began to capture from now on . If it is set to false it began from where it left off. Could you please check it ?
Thanks

**Comment by schdai** [comment]
thanks .
