### ISSUE TITLE
Failed to get logMinerData by logMinerSelect.executeQuery();

### ISSUE THREAD

**Issue by yymoxiaochi** [erdemcer/kafka-connect-oracle#63]
I have a problem. I failed to  get logMinerData by ` logMinerSelect.executeQuery();`
when I set 'reset.offset'  is true , offset value will be set to current SCN of database when connector started. But ,` logMinerSelect.executeQuery();` is executed all the time ，no result for a long time. I use oracle client ,and start with this current scn still this case.
Is there something wrong?

**Comment by erdemcer** [comment]
What is your db version ?  logminerdata.executequery is executed 1 time when connector started if your db version below 19c.  If your version is 19c executequery is executed every 5 seconds.
Despite transaction (DML) occur , you could not get result ?

**Comment by yymoxiaochi** [comment]
My db version is 11.2.0.4.0.
And I can get result after do some DML, so if  i want start a connector with current scn , I have to do some database operations in the whitelist immediately？

**Comment by erdemcer** [comment]
No,you do not have to do some operations immediately. Connector listens v$logmnr_contents view continuously.When DML occurs , connector populates the operations to Kafka topic.

**Comment by yymoxiaochi** [comment]
Wow , I do some tests. it's working ,Thank very much.
