### ISSUE TITLE
Problem with empty non-null values and UTF8

### ISSUE THREAD

**Issue by berk-b** [erdemcer/kafka-connect-oracle#65]
Hi,
I have a table with some fields filled with '' (it's not null) values in Oracle DB, and I can't change that. Your connector perfectly handles the update operations, but when I flush the SQL_REDO from the topic to my Postgres DB (also in UTF8), it fails with "PSQLException: ERROR: invalid byte sequence for encoding \"UTF8\": 0x00" because in topic, the values of those fields become '\u0000' instead of '' in Oracle. Is there any way to replace it with something like ' ', without modifying the source tables.
Thank you!

**Comment by erdemcer** [comment]
Hi,
After capturing data from Oracle , before populating this data to Postgres you can change captured data.Replace or rewrite is possible for SQL_REDO if you write some code . 

But I think you mention , without writing code you would like to create topic messages as you like ?
Thanks

**Comment by berk-b** [comment]
Thank you for clarification. 
I could get rid of those '\u0000' by adding
sqlRedo = sqlRedo.replaceAll("[^\\u0009\\u000a\\u000d\\u0020-\\uD7FF\\uE000-\\uFFFD]", " ");

**Comment by berk-b** [comment]
The problem is solved, it was a data issue. 
Thank you for robust, clear and fast connector.

**Comment by erdemcer** [comment]
Thank you very much.
