### ISSUE TITLE
can I only capture the update operation?

### ISSUE THREAD

**Issue by bellacat82** [erdemcer/kafka-connect-oracle#68]
can I only capture the update operation?
Now it is capture all DML operation

**Comment by erdemcer** [comment]
By default as you said it captures all DMLs and creates Kafka message with operation field contains DML type.You can consume only UPDATE messages.
And of course with some development , it can be controlled by config parameter in order to capture only specifed operation types.
Thanks

**Comment by bellacat82** [comment]
Which config parameter can control the operation type?
Thank you

**Comment by erdemcer** [comment]
Actually there is no parameter yet . After development it can be done .

**Comment by bmatticus** [comment]
I can take a look at this one, should be pretty simple I think.

**Comment by erdemcer** [comment]
Hi,
PR 68 for this issue  have been merged . 
Thanks for contribution.
