### ISSUE TITLE
Error during poll on topic (invalid value: null used for required field ID)

### ISSUE THREAD

**Issue by AvinashUrs** [erdemcer/kafka-connect-oracle#70]
Hi,

I'm facing the issue after alter statement in this scenario 

"alter table test1 add constraint test_pk primary key(id);"
 update test1 set city='Mumbai' where city='Bombay'

Error:
![image018](https://user-images.githubusercontent.com/50581776/85698071-f3b31a80-b6f7-11ea-97d3-c2c616ec070f.jpg)

Thank you.

**Comment by AvinashUrs** [comment]
Hi,

I'm facing the issue after alter statement in this scenario 

"alter table test1 add constraint test_pk primary key(id);"
 update test1 set city='Mumbai' where city='Bombay'

Error:
![image018](https://user-images.githubusercontent.com/50581776/85698071-f3b31a80-b6f7-11ea-97d3-c2c616ec070f.jpg)

Thank you.

**Comment by erdemcer** [comment]
Hi,
Firstly could you please check supplemental logging from your v$database view ?

`select v."SUPPLEMENTAL_LOG_DATA_MIN",v."SUPPLEMENTAL_LOG_DATA_PK",v."SUPPLEMENTAL_LOG_DATA_UI",
       v."SUPPLEMENTAL_LOG_DATA_ALL"
 from v$database v `

**Comment by AvinashUrs** [comment]
Hi 

Below is the result:

![Capture2](https://user-images.githubusercontent.com/50581776/85704964-6fb06100-b6fe-11ea-9259-76fcd4b02dec.png)

Thank you.

**Comment by erdemcer** [comment]
Hi,
Could you please execute following command mentioned in Readme in order to capture all fields of data and retest the issue ?
```sql 
alter database add supplemental log data (all) columns; 
```
Thanks

**Comment by AvinashUrs** [comment]
Hi 
Still the issue is same.

**Comment by erdemcer** [comment]
Hi,
1. Before alter statement , did you encounter problem ?
2.If you did not could you please send table information , sql (DML) statements and kafka messages if you have consumed 
3. Could you please send the output of sql  you executed to get supplemental logging information ?

Thanks.

**Comment by AvinashUrs** [comment]
Hi,
Sorry for the delayed response,after altering supplemental log and restarting connector its working fine. 
did not checked it properly that time.

May i know what is the use of capturing all the columns for update and delete where i have used it one ?

Thank you for helping out with the solution.

**Comment by erdemcer** [comment]
Hi,
Data structs for update and delete DMLs are based on all columns of table.These data structs are not created dynamically for each DML. 
Of course we do not have to take all columns which are not affected by update or delete. But first design of connector is developed on this. This can be changed .
Thanks
