### ISSUE TITLE
can not capture other fields value when update one field only 

### ISSUE THREAD

**Issue by oushu1miaoqing1** [erdemcer/kafka-connect-oracle#80]
that filed should in where clause or in other places .Otherwise we can not update target by pk.

**Comment by erdemcer** [comment]
Hi,
What is your supplemental logging level ? If it is "all columns"  all fields of table is written to log redo  . Could you please check it out ? 
Thanks.

**Comment by oushu1miaoqing1** [comment]
the problem has been solved, Thanks.

**Comment by erdemcer** [comment]
Thank you.
