### ISSUE TITLE
Captured archive and log files have changed , regetting log files (com.ecer.kafka.connect.oracle.LogMinerThread:139)

### ISSUE THREAD

**Issue by fengant** [erdemcer/kafka-connect-oracle#87]

**Comment by erdemcer** [comment]
Hi,
If archiving is faster than mining process , capture process can miss data. So if connector gets like issue , it stops capturing and gets archive and log files into list to capture again.
Thanks.

**Comment by fengant** [comment]
Hi,erdemcer
But now the connector has been looping to stop capturing and gets archive and log files into list to capture again.

**Comment by fengant** [comment]
like this  
![image](https://user-images.githubusercontent.com/42595025/94384203-90140f80-0174-11eb-8587-06fef22740c1.png)

**Comment by erdemcer** [comment]
Hi,
Could you please send whole output as a file ?
Thanks

**Comment by fengant** [comment]
HI,erdemcer

[connect.zip](https://github.com/erdemcer/kafka-connect-oracle/files/5295889/connect.zip)

**Comment by erdemcer** [comment]
Hi,
As i have seen you db version is 11g and you are using test purpose release 1.0.68_x ? if it is please do not use this release . 
Thanks

**Comment by fengant** [comment]
thank you

**Comment by fengant** [comment]
Hi erdemcer,
   i am using db version is 11g and kafka-connect-oracle is using release 1.0.
  ![image](https://user-images.githubusercontent.com/42595025/95695873-717d4080-0c6b-11eb-8d2e-32bd5130345e.png)
  can you help me ?
Thanks

**Comment by fengant** [comment]
> Hi,
> As i have seen you db version is 11g and you are using test purpose release 1.0.68_x ? if it is please do not use this release .
> Thanks

Hi erdemcer,
i am using db version is 11g and kafka-connect-oracle is using release 1.0.
![image](https://user-images.githubusercontent.com/42595025/95695945-bdc88080-0c6b-11eb-97c7-a4c031fc60f6.png)

can you help me ?
Thanks

**Comment by erdemcer** [comment]
Hi,
I will update soon.
Thanks
