### ISSUE TITLE
What are the reasons for these differences about DESUPPORT_CM

### ISSUE THREAD

**Issue by yymoxiaochi** [erdemcer/kafka-connect-oracle#93]
Hi, erdemcer. there are so many differences between 19c and 12c, I just know 19c not support CM, but why don't you use "commit_data_only" option? and In class LogMinerThread, there are so many operating judgment, I want to know why， thanks.

**Comment by erdemcer** [comment]
Hi,
commit_data_only option populates content of logminer commit_scn column order and it is hard to manage logminer by using commit_scn column. Logminer procedures or functions use scn column. 
While i was testing connector i have used commited_data_only option and used scn column to order data not to skip any data . But order of scn has slow performance . Finally i have deciced to use all transation states to get better performance.

But besides this i am working on commited_data_only option with scn order nowadays.
Thanks
