### ISSUE TITLE
Compilation error. Java version related?

### ISSUE THREAD

**Issue by vinilneves** [erdemcer/kafka-connect-oracle#96]
Hi!

I have a build error and was wondering if it's java version related. Which java version do I need to use? You should add this information to the readme at some kind of 'requirements' section.

I tried to build it inside an `openjdk:7` container and got this:

```bash
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project kafka-connect-oracle: Compilation failure
/usr/src/myapp/src/main/java/com/ecer/kafka/connect/oracle/LogMinerThread.java:[253,31] error: cannot find symbol
```

**Comment by vinilneves** [comment]
Also providing compiled artifacts at the releases page would be even better...

**Comment by vinilneves** [comment]
It seems it worked using `openjdk:8`

**Comment by erdemcer** [comment]
Hi,
connector is written by using jdk:8 . Yes Readme should be updated with this information . I will consider it.
Thanks

**Comment by vinilneves** [comment]
Thank you @erdemcer
